// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWRJGbel2piZ_0T11RaTTxU0r_Is2W6dE',
    appId: '1:423280339315:web:cc9cf7e748c1c3ec8f7d06',
    messagingSenderId: '423280339315',
    projectId: 'signup-b86a3',
    authDomain: 'signup-b86a3.firebaseapp.com',
    storageBucket: 'signup-b86a3.appspot.com',
    measurementId: 'G-JRRSHNGJKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLzO_Mctsz60DmFCgvyM0jzJmhnQBOi-g',
    appId: '1:423280339315:android:094370ce0be364f28f7d06',
    messagingSenderId: '423280339315',
    projectId: 'signup-b86a3',
    storageBucket: 'signup-b86a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiT6GnfOxiqCLgZ50G-WaYSfXpS7BHLpQ',
    appId: '1:423280339315:ios:f80cd19f5e7fecc68f7d06',
    messagingSenderId: '423280339315',
    projectId: 'signup-b86a3',
    storageBucket: 'signup-b86a3.appspot.com',
    iosClientId: '423280339315-ve6h0ptrga21aj7ma1r3l37e7qev33es.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiT6GnfOxiqCLgZ50G-WaYSfXpS7BHLpQ',
    appId: '1:423280339315:ios:af56cd78999623d38f7d06',
    messagingSenderId: '423280339315',
    projectId: 'signup-b86a3',
    storageBucket: 'signup-b86a3.appspot.com',
    iosClientId: '423280339315-t3tmpjps3qi0vmueuptdi2b4sefr1ukf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSignup.RunnerTests',
  );
}
